# Generated by Django 6.0 on 2026-01-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
