# Generated by Django 6.0 on 2026-01-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_consultationrequest_preferred_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='preferred_time',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='region',
        ),
    ]
